server:
  port: ${PORT:8097}

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  timeout: ${REDIS_TIMEOUT:10000}
  password: ${REDIS_PASSWORD:}
  poolConfig:
    minIdle: ${REDIS_POOL_MIN_IDLE:10}
    maxIdle: ${REDIS_POOL_MAX_IDLE:50}
    maxTotal: ${REDIS_POOL_MAX_TOTAL:50}

---
spring:
    profiles:
        active: ${PROFILE:local}
    jackson:
        default-property-inclusion: NON_NULL
